# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49d21fb07b258930c6f94a52438276333d3dba1a6d0816b5dd56fcf5b038b7f3f6d8c596d8b8ad750fa7cf53b13dc0cfc97abc20064c8906eeba4e5a52bcee66

test:
  secret_key_base: 06a2e5479720fe543f6c54459bf3828d2dd0c0a6eb5e70f09da6f9916f67b52e051b2e162be7555fe8749953e3fedfe966e4eaee78df65e152fa7f06ec029daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
